apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              cpu: "100m" # Minimum guaranteed CPU
              memory: "128Mi"
            limits:
              cpu: "500m" # Max CPU
              memory: "256Mi"
          ports:
            - containerPort: 80
