name: CI Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  REGISTRY: ${{ secrets.REGISTRY }}
  CHART_NAME: demo-chart
  NAMESPACE: demo
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASS }}

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: ./k8s-pilot-demo/app
        file: ./k8s-pilot-demo/app/Dockerfile
        push: true
        tags: docker.io/${{ secrets.REGISTRY_USER }}/demo-app:${{ github.sha }}

    - name: Trivy Scan
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: docker.io/${{ secrets.REGISTRY_USER }}/demo-app:${{ github.sha }}
        exit-code: 0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: ${{ secrets.AKS_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}

    - name: Install Helm v3
      run: |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Set working directory
      run: |
        pwd
        ls -la
        ls -la k8s/k8s-pilot-demo/helm/demo-chart

    - name: Helm Deploy
      working-directory: ${{ github.workspace }}
      run: |
        helm upgrade --install demo-chart ./k8s-pilot-demo/k8s/helm/demo-chart \
        --namespace demo --create-namespace \
        --set image.repository=${{ env.REGISTRY }}/demo-app \
        --set image.tag=05965dcb5f816499d043aab198266ef95430ba93


    - name: Verify chart path
      run: |
        test -f ./k8s/helm/demo-chart/Chart.yaml && echo "Chart found" || echo "Chart missing"


    - name: Run smoke test
      run: |
        kubectl wait --for=condition=available --timeout=120s deployment/${{ env.CHART_NAME }} -n ${{ env.NAMESPACE }} || true
        kubectl get pods -n ${{ env.NAMESPACE }} -o wide
