name: CI Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  REGISTRY: ${{ secrets.REGISTRY }}
  CHART_NAME: demo-chart
  NAMESPACE: demo
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASS }}

    - name: Build and push image (buildx)
      uses: docker/build-push-action@v4
      with:
        context: ./k8s-pilot-demo/app       
        file: ./k8s-pilot-demo/app/Dockerfile
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/demo-app:${{ github.sha }}

    - name: Trivy Scan
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: ${{ env.REGISTRY }}/demo-app:${{ github.sha }}
        exit-code: 1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: ${{ secrets.AKS_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}

    - name: Install Helm
      uses: azure/setup-helm@v1

    - name: Update Helm values and deploy
      run: |
        helm upgrade --install ${{ env.CHART_NAME }} k8s/helm/${{ env.CHART_NAME }}           --namespace ${{ env.NAMESPACE }} --create-namespace           --set image.repository=${{ env.REGISTRY }}/demo-app           --set image.tag=${{ github.sha }}
    - name: Run smoke test
      run: |
        kubectl wait --for=condition=available --timeout=120s deployment/${{ env.CHART_NAME }} -n ${{ env.NAMESPACE }} || true
        kubectl get pods -n ${{ env.NAMESPACE }} -o wide
